### ISSUE TITLE
Nestings: Inconsistent handling of 'null' in outer property

### ISSUE THREAD

**Issue by acepe** [CodeFX-org/LibFX#9]
Hello Nicolai,
I just noticed some inconsistencies with handling null-values in Nestings.
If you create a nesting, and the outer property ('currentEmployeeProperty' in your example) contains 'null', a NullPointerExcepton is thrown.
However if the nesting was already created (using a non-null Employee) and the currentEmployeeProperty's value is set to 'null' at a later time, no exception is thrown.Additionally, the NestedProperty is not updated and keeps its old value. I have created [a simple test] (https://gist.github.com/acepe/620d9a268106641aff19) showing the behaviour.

I know that 'null' in the outer property (Employee) is ambigous. What should happen if there is a Nesting on, for example Employee::nameProperty, the Employee is null, and the Name is changed? Either a Exception could be thrown (there is no Employee  whose name can be set), or a new Employee could be created, and the name set.

I would personally really like it if Nestings could handle both described alternatives. 
* If the outer properties value becomes 'null', the inner property should become null, too (not keep its last value, as it is currently). 
* Throwing a NullPointerException could be the default way of handling 'null' in outer properties when *writing* to inner-properties. 
* As an alternative one could specifiy an optional Supplier, which creates a new value for the outer property.

**Comment by nicolaiparlog** [comment]
Hi @acepe,

thanks for this detailed description! I'll look into it as soon as I find some time.

**Comment by nicolaiparlog** [comment]
I found some time to look into the matter:

#### NPE During Construction

As the code is written at the moment, `NullPointerException`s should never occur. That it does when the outer observable (or any other observable, really) contains null, is a bug. Thank you for spotting it! Great work (and also awesome that you provided a test! :+1: ).

I squashed it in e46cc83 and will soon release a version 0.2.1 which contains the fix.

#### Setting Null (Present)

The behavior you observe when one of the observables gets a null value is as intended (see [Javadoc for NestedProperty](http://libfx.codefx.org/javadoc/org/codefx/libfx/nesting/property/NestedProperty.html)).

In short: When one of the observables gets a null value, the inner observable can not be accessed anymore (is _missing_). But the nested property does not take on a new value - this is largely due to the fact that it is unclear what this value would be (null is ambiguous and not possible for primitive wrapping properties). To give you an opportunity to deal with this scenario, the property has an [`innerObservablePresentProperty`](http://libfx.codefx.org/javadoc/org/codefx/libfx/nesting/Nested.html#innerObservablePresentProperty) which indicates this.

Just to avoid misunderstandings: It would be great if you could confirm that the behavior described here and in the documentation is what you observe. As soon as you do, I will release 0.2.1.

#### Setting Null (Future)

That behavior is stupid. :wink: Well, not really but it isn't great either. And your suggestions are very much in line with what I had in mind but didn't implement yet.

If you open another ticket (which I will mark as a feature request), we can discuss which options exist and I will implement it for 0.3.0 which I plan for sometime in May.

**Comment by acepe** [comment]
Hello @nicolaiparlog. Thanks for the quick fix. I tested it, setting null works as described.

**Comment by nicolaiparlog** [comment]
Ok, I will release 0.2.1 this afternoon (hopefully).

Btw, regarding the future of *Setting Null*, see #3. We can discuss your ideas there.

**Comment by nicolaiparlog** [comment]
I just released [0.2.1](https://github.com/CodeFX-org/LibFX/releases/tag/v0.2.1) which contains this fix.
